
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/esphome/esphome
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2025.11.3"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

configs:
  repo: https://github.com/nolte/esphome-configs.git
  revision: master

crons:
  "nous-a1t-05":
    config: "nous-a1t-05.yaml"
    address: "192.168.178.76"
    suspend: true
  "gosund-sp111-01":
    config: gosund-sp111-01.yaml
    address: "192.168.178.41"
    suspend: true