apiVersion: v2
name: keycloak
description: Preconfigured keycloak Deployment
type: application
version: 0.2.2
sources:
  - https://codecentric.github.io/helm-charts
  - https://github.com/codecentric/helm-charts/tree/master/charts/keycloak
dependencies:
  - name: keycloak
    version: 15.0.2
    repository: https://codecentric.github.io/helm-charts

  - name: argo-workflows-execution
    version: 0.0.1
    repository: "file://../../../argo-workflow-templates/deploy/chart"
