# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: flow-tf-powerdns-baseline
  labels:
{{ include "powerdns.labels" . | indent 4 }}
spec:
  entrypoint: exec
  arguments:
    parameters:
    - name: revision
      value: "feature/applications-structures" #master
    - name: action
      value: apply
    - name: path
      value: ./src/applications/powerdns/configuration/baseline

  templates:  
  - name: exec
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "argo-workflows"
        vault.hashicorp.com/agent-inject-token: "true"
        # Load a Secret for Terraform State file access
        vault.hashicorp.com/agent-inject-secret-pdnsaccess: secrets-tf/services/dns/users/root
        vault.hashicorp.com/agent-inject-template-pdnsaccess: |
          {{"{{-"}} with secret "secrets-tf/services/dns/users/root" {{ "-}}" }}
          export PDNS_API_KEY={{"{{"}} .Data.data.token {{ "}}" }}
          {{"{{-"}} end {{ "}}" }}
        vault.hashicorp.com/agent-inject-secret-s3access: secrets-tf/services/s3/users/admin
        vault.hashicorp.com/agent-inject-template-s3access: |
          {{"{{-"}} with secret "secrets-tf/services/s3/users/admin" {{ "-}}" }}
          [default]
          aws_access_key_id={{"{{"}} .Data.data.accesskey {{ "}}" }}
          aws_secret_access_key={{"{{"}} .Data.data.secretkey {{ "}}" }}
          {{"{{-"}} end {{ "}}" }}
    inputs:
      parameters:
      - name: revision
        default: "feature/applications-structures" #master
      - name: action
        default: apply
      - name: path
        default: ./src/applications/powerdns/configuration/baseline
      artifacts:
      - name: argo-source
        path: "/src"
        git:
          repo: "https://github.com/nolte/argo-charts.git"
          revision: "{{ "{{" }}inputs.parameters.revision{{ "}}" }}"
    script:
      image: alpine/terragrunt
      command: [bash]
      workingDir: "/src"
      source: |
        #!/usr/bin/env bash
        set -o errexit
        set -o pipefail
        set -o nounset
        cd {{ "{{" }}inputs.parameters.path{{ "}}" }}
        source /vault/secrets/pdnsaccess
        export VAULT_TOKEN=$(cat /vault/secrets/token)
        terragrunt {{ "{{" }}inputs.parameters.action{{ "}}" }} -input=false -auto-approve -no-color

      env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /vault/secrets/s3access
        - name: PDNS_SERVER_URL
          value: http://powerdns-webserver.{{.Release.Namespace}}.svc:8081
      envFrom:
        - configMapRef:
            name: tf-static-endpoints