apiVersion: v2
name: tpl-argocd-baseline
version: 1.1.2
appVersion: 1.0.1
sources:
- https://github.com/goharbor/harbor
- https://github.com/goharbor/harbor-helm
dependencies:
  - name: common-app
    repository: https://nolte.github.io/argo-charts/
    version: 1.2.0