apiVersion: v2
dependencies:
  - name: esphome
    repository: https://k8s-at-home.com/charts/
    version: 8.0.0
description: Preconfigured ESPHome Deployment
name: esphome
sources:
  - https://github.com/k8s-at-home/charts/tree/master/charts/stable/esphome
type: application
version: 0.0.1