apiVersion: {{ include "common.capabilities.application.apiVersion" . }}
kind: Application
metadata:
  name: {{ include "common.names.fullname" . }}
  finalizers:
  {{- include "common.finalizers" . | nindent 4 }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.controllerLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.controllerAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  destination:
  {{- with .Values.destination }}
  {{- toYaml . | nindent 4 }}
  {{- end }}

  project: {{ .Values.project }}
  source:
  {{- include "common.classes.source" . | nindent 4 }}
    helm:
      releaseName:  {{ .Values.releaseName }}
      values: |
        argocd-project-contour:
          enabled: {{.Values.projectContour.enabled}}
          project: {{.Values.global.project}}
        argocd-cert-manager:
          enabled: {{.Values.certManager.enabled}}
          project: {{.Values.global.project}}
          source:
            helm:        
              values: |
                installCRDs: true
                prometheus:
                  enabled: true
                  servicemonitor:
                    enabled: true
        argocd-forecastle:
          enabled: {{.Values.certManager.enabled}}
          project: {{.Values.global.project}}
          syncPolicy:
            automated: {}
            syncOptions:
              - CreateNamespace=true          
          source:
            helm:
              values: |
                forecastle:
                  ingress:
                    enabled: {{.Values.forecastle.ingress.enabled}}
                    annotations:
                      ingress.kubernetes.io/force-ssl-redirect: "true"
                      cert-manager.io/cluster-issuer: {{.Values.global.clusterIssuer}}
                    tls:
                      - hosts:
                          - forecastle.{{.Values.global.domain}}
                        secretName: forecastle-cert
                    hosts:
                      - host: forecastle.{{.Values.global.domain}}
                        paths:
                        - /        
        argocd-monitoring:
          enabled: {{.Values.certManager.enabled}}
          project: {{.Values.global.project}}
        argocd-reloader:
          enabled: {{.Values.reloader.enabled}}
          project: {{.Values.global.project}}
        argocd-konfigurator:
          enabled: {{.Values.konfigurator.enabled}}
          project: {{.Values.global.project}}
  syncPolicy:
  {{- with .Values.global.syncPolicy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ignoreDifferences }}
  ignoreDifferences:
  {{- toYaml . | nindent 4 }}
  {{- end }}