apiVersion: v2
dependencies:
  - name: home-assistant
    alias: homeassistant 
    repository: https://k8s-at-home.com/charts/
    version: 10.0.0
description: Preconfigured Home Assistant Deployment
name: home-assistant
sources:
  - https://github.com/k8s-at-home/charts/tree/master/charts/stable/home-assistant
type: application
version: 0.2.2