apiVersion: v2
dependencies:
  - name: forecastle
    repository: https://stakater.github.io/stakater-charts
    version: v1.0.68
description: Preconfigured forecastle Deployment
name: forecastle
sources:
  - https://stakater.github.io/stakater-charts
  - https://github.com/stakater/Forecastle/tree/master/deployments/kubernetes/chart/forecastle
type: application
version: 0.2.2