apiVersion: v2
dependencies:
  - name: harbor
    repository: https://helm.goharbor.io
    version: 1.7.1
description: Preconfigured harbor Deployment
name: harbor
sources:
  - https://github.com/goharbor/harbor-helm
  - https://github.com/goharbor/harbor
  - https://goharbor.io/
type: application
version: 0.0.1